# Generated by Django 5.0.4 on 2024-04-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auction_user_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
