# Generated by Django 5.0.4 on 2024-04-09 07:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_searcher", "0002_alter_fileupload_status_alter_fileupload_upload_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 7, 11, 55, 435177)
            ),
        ),
        migrations.CreateModel(
            name="FileAnalyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_analyzer",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "error_classifier",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("sentiment", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "categories",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 9, 7, 11, 55, 435816)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("success", "Success"),
                            ("partial_success", "Partial Success"),
                        ],
                        default="processing",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_upload",
                        to="file_searcher.fileupload",
                    ),
                ),
            ],
        ),
    ]
