# Generated by Django 5.0.4 on 2024-04-09 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_searcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("failed_deletion", "Failed Deletion"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 5, 34, 16, 524970)
            ),
        ),
    ]
