# Generated by Django 5.0.4 on 2024-04-09 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_searcher", "0003_alter_fileupload_upload_time_fileanalyzer"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileanalyzer",
            name="error",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="fileanalyzer",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 7, 45, 0, 424193)
            ),
        ),
        migrations.AlterField(
            model_name="fileanalyzer",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("partial_success", "Partial Success"),
                    ("download_file_failed", "Download Fail"),
                    ("save_local_file_failed", "Save Local File Fail"),
                    ("extract_text_failed", "Extract Text Fail"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 7, 45, 0, 423686)
            ),
        ),
    ]
