# Generated by Django 5.0.4 on 2024-04-09 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "file_searcher",
            "0004_fileanalyzer_error_alter_fileanalyzer_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileanalyzer",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 9, 36, 0, 944601)
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 9, 36, 0, 944081)
            ),
        ),
    ]
