# Generated by Django 5.0.4 on 2024-04-10 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_searcher", "0006_fileanalyzer_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="google_drive_id",
            new_name="file_path",
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 10, 0, 25, 44, 867607)
            ),
        ),
    ]
